### PR TITLE
Add IPFS support behind cli flag

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds back the `IpfsDatastore` from the demo branch.  It's disabled by default but can be enabled with the `-i` or `--use_ipfs` cli flag.  You can also pass in `--ipfs_host` and `--ipfs_port` if you need to.

If enabled, ipfs is only used for "raw" data.  I added a `mediachain.datastore.get_raw_datastore()` function which will return the ipfs store if the flag is set or the default dynamo db otherwise.

`get_raw_datastore()` is used for the images and the raw metadata when writing, and to fetch thumbnails and convert to base64 when reading.

Oh, and I stuck the commit that converts `@link` maps to base58 strings in here as well.

### CODE REVIEW

**Comment by yusefnapora** [comment]
oh, wait a second...

I just realized that using ipfs for the raw metadata in the  `metaSource` field will probably break vyzo's S3 backing store, since it won't be able to resolve those refs...

I can add the ipfs link back into `meta.raw_ref` if you want @parkan

**Comment by parkan** [comment]
hmm ok yeah let's put it in `meta.raw_ref` for the moment, but I think overall we shouldn't be shying away from IPFS

**Comment by yusefnapora** [comment]
yeah, I agree; I wonder though if we should be using [multiaddr](https://github.com/jbenet/multiaddr) instead of raw base58 multihashes... we could define our own "scheme" for dynamo refs and use the official ipfs scheme for ipfs

**Comment by parkan** [comment]
totally, let's do it

**Comment by parkan** [comment]
(I think the semantics are that a multiaddr w/o a protocol specifier is an ipfs link by default, but we can make it explicit)

**Comment by yusefnapora** [comment]
sweet, I made an issue on the server repo, since it will need support there: https://github.com/mediachain/mediachain/issues/141

**Comment by parkan** [comment]
Hmm having merged this I'm seeing successful writes that I can't read back:

```
(venv) [getty]% mediachain -s 54.88.3.43 -p 10001 -t Test -k $MC_AWS_ACCESS_KEY_ID -x $MC_AWS_SECRET_ACCESS_KEY --use_ipfs ingest getty_custom
deduplicating getty artists.  This may take a while...
Parsed 1 entries, 1 unique artists
done deduplicating artists
Ingested getty image 'getty_JD6484-001' MultihashReference: QmUDRw46Y7f9gAxpS2ykcyTpSKRBERYR1kjnZbH77TwZCz
(venv) [getty]% mediachain -s 54.88.3.43 -p 10001 -t Test -k $MC_AWS_ACCESS_KEY_ID -x $MC_AWS_SECRET_ACCESS_KEY get QmUDRw46Y7f9gAxpS2ykcyTpSKRBERYR1kjnZbH77TwZCz
Traceback (most recent call last):
  File "/Users/arkadiy/mine/mediachain-client/venv/bin/mediachain", line 11, in <module>
    sys.exit(main())
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/cli/main.py", line 152, in main
    fn(ns)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/cli/main.py", line 140, in <lambda>
    'get': lambda ns: api.get_and_print_object(ns.host, ns.port, ns.object_id),
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/reader/api.py", line 14, in get_and_print_object
    obj = get_object(host, port, object_id)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/reader/api.py", line 43, in get_object
    return fetch_thumbnails(obj)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/reader/api.py", line 61, in fetch_thumbnails
    thumb = db.get(thumb_ref)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/datastore/dynamo.py", line 110, in get
    byte_string = bytes(item['Item']['data'])
```

**Pull request merged**
